addressbook/urls.py
from django.conf.urls import patterns, url

from addressbook import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^(?P<record_id>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^addrecord/$', views.addrecord, name="addrecord"),
    url(r'^submitrecord/$', views.submitrecord, name="submitrecord"),
)

project_sw/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^addressbook/', include('addressbook.urls', namespace="addressbook")),
    url(r'^admin/', include(admin.site.urls)),
)

addressbook/models.py
from django.db import models

class Title(models.Model):
    # example table for titles available
    title_name = models.CharField(max_length=5)
    def __unicode__(self):
        return self.title_name

class City(models.Model):
    # example table of cities, populated with only a few examples
    # table can be populated using source files listing all cities
    city_name = models.CharField(max_length=30)
    def __unicode__(self):
        return self.city_name

class County(models.Model):
    # example table of counties, populated with only a few examples
    # as above, table can be populated using source files listing all counties
    county_name = models.CharField(max_length=30)
    def __unicode__(self):
        return self.county_name

class Record(models.Model):
    # stores all attributes provided
    # some attributes, such as title, city and county can be selected by drop down
    # such predictable attributes are best stored in a seperate table
    # enables more fluid population of drop down menus and improved normalisation
    title = models.ForeignKey(Title)
    firstname = models.CharField(max_length=30)
    surname = models.CharField(max_length=30)
    address_line_1 = models.CharField(max_length=30)
    address_line_2 = models.CharField(max_length=30, blank=True, null=True)
    address_line_3 = models.CharField(max_length=30, blank=True, null=True)
    city = models.ForeignKey(City)
    county = models.ForeignKey(County)
    postcode = models.CharField(max_length=8)
    def __unicode__(self):
        st = self.title.title_name + " " + self.firstname + " " + self.surname
        return st
    def get_name(self):
        st = self.title.title_name + " " + self.firstname + " " + self.surname
        return st
    def get_address(self):
        st = self.address_line_1 + ",\n" + self.address_line_2 + ",\n" + self.address_line_3
        return st
    get_address.short_description = 'Address'
    get_name.short_description = 'Name'

addressbook/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.template import RequestContext, loader
from django.views import generic

from addressbook.models import Record, Title, City, County

def index(request):
   # latest_record_list = Record.objects.order_by('surname')
    latest_record_list = Record.objects.all().extra(select={'lower_name':'lower(surname)'}).order_by('lower_name')
    context = {'latest_record_list':latest_record_list }
    return render(request, 'addressbook/index.html', context)

"""
class IndexView(generic.ListView):
    template_name = 'addressbook/index.html'
    context_object_name = 'latest_record_list'
    def get_queryset(self):
        return Record.objects.order_by('-surname')
"""

"""
def detail(request, record_id):
    record = get_object_or_404(Record, pk=record_id)
    return render(request, 'addressbook/detail.html', {'record':record})
"""

class DetailView(generic.DetailView):
    model = Record
    template_name = 'addressbook/detail.html'

"""
DetailView requires a pk, which we dont have yet (could get one, but why when the view below works)
class AddrecordView(generic.DetailView):
    model = Record
    template_name = 'addressbook/addrecord.html'
"""

def addrecord(request):
    ## objects come from database, so for busy apps, populating elements with such objects may not be wise (not noticeable slower but database could crash)
    titles = Title.objects.all()
    cities = City.objects.all()
    counties = County.objects.all()
    context = { 'titles': titles, 'cities': cities, 'counties': counties }
    return render(request, 'addressbook/addrecord.html', context)

def submitrecord(request):
    #create new record
    r = Record()

    ## get drop down menu objects
    t = get_object_or_404(Title, pk=request.POST['title'])
    ci = get_object_or_404(City, pk=request.POST['city'])
    co = get_object_or_404(County, pk=request.POST['county'])
    
    ##set values to new record
    r.title = t
    r.firstname = request.POST['forename']
    r.surname = request.POST['surname']
    r.address_line_1 = request.POST['address_line_1']
    r.address_line_2 = request.POST['address_line_2']
    r.address_line_3 = request.POST['address_line_3']
    r.city = ci
    r.county = co
    r.postcode = request.POST['postcode']

    r.save()
    return HttpResponseRedirect(reverse('addressbook:index'))

            

templates/addressbook/addrecord.html
{% load bootstrap3 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% bootstrap_messages %}

<h1> Add Record </h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'addressbook:submitrecord' %}" method="post" class="form">
{% csrf_token %}

<!-- form elements for addressbook -->
<table>
<!-- name -->
<tr>
<td><label>Title: </label></td>
<td>
<select name="title">
{% for title in titles %}
<option value="{{ title.id }}"> {{ title }} </option>
{% endfor %}
</select>
</td>
</tr>

<!-- firstname and surname -->
<tr>
<td><label>Firstname: </label></td>
<td><input type="text" name="forename"></td>
</tr>

<tr>
<td><label>Surname: </label></td>
<td><input type="text" name="surname"></td>
</tr>

<!-- address lines -->
<tr>
<td><label>Address Line 1: </label></td>
<td><input type="text" name="address_line_1"></td>
</tr>

<tr> 
<td><label>Address Line 2: </label></td>
<td><input type="text" name="address_line_2"></td>
</tr>

<tr>
<td><label>Address Line 3: </label></td>
<td><input type="text" name="address_line_3"></td>
</tr>

<!-- city and county drop down -->
<tr>
<td><label>City: </label></td>
<td><select name="city">
{% for city in cities %}
<option value="{{ city.id }}"> {{ city }} </option>
{% endfor %}
</select></td>
</tr>

<tr>
<td><label>County: </label></td>
<td><select name="county">
{% for county in counties %}
<option value="{{ county.id }}"> {{ county }} </option>
{% endfor %}
</select></td>
</tr>

<!-- post code -->
<tr>
<td><label>Postcode: </label></td>
<td><input type="text" name="postcode"></td>
</tr> 

<tr>
<td>
<input type="submit" value="Submit Record" />
</td>
</tr>
</table>

<br />
<a href={% url 'addressbook:index' %}> Back to Addressbook </a>
</form>

templates/addressbook/detail.html
<h1>{{ record.get_name }}</h1>
<p>{{ record.get_address }} </p>

templates/addressbook/index.html
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% if latest_record_list %}

	<table class="table table-condensed table-striped">
		<tr>
			<th>Title</th>
			<th>First name</th>
			<th>Last name</th>
			<th>City</th>
			<th>Postcode</th> 
		</tr>
	
		{% for record in latest_record_list %}
	
			<tr>
				<td>{{ record.title }} </td>
				<td>{{ record.firstname }} </td>
				<td>{{ record.surname }} </td>
				<td>{{ record.city }} </td>
				<td>{{ record.postcode }} </td>
			</tr>
	
		{% endfor %}
	
	</table>
{% else %}
	<p>No records available </p>
{% endif %}
<a href="{% url 'addressbook:addrecord' %}"> Add Record </a>